    spring.application.name=demo
    spring.datasource.url=jdbc:mysql://localhost:3309/data_English?createDatabaseIfNotExist=true
    spring.datasource.username=root
    spring.datasource.password=123456
    spring.jpa.hibernate.ddl-auto=update
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


    signer.key=RHqB3EkQRVRwaVRlAj/Um3cm5mGtFg5XMYHKpSXa4vX02SzaMlUGpm8bi80tJNZJ

    valid-duration:500
    refeshable-duration:2000


    upload.path=C:/Users/DELL/Downloads/demoEnglishSpringBoot/src/main/resources/static/images/
    spring.servlet.multipart.enabled=true
    spring.servlet.multipart.max-file-size=100MB
    spring.servlet.multipart.max-request-size=110MB

    file.upload-dir=C:/Users/DELL/Downloads/demoEnglishSpringBoot/src/main/resources/static/audio
    spring.web.resources.static-locations=classpath:/static/
    spring.mail.host=smtp.gmail.com
    spring.mail.port=587
    spring.mail.username=cong201120001@gmail.com
    spring.mail.password=nfil jgsx ajts bssf
    spring.mail.properties.mail.smtp.auth=true
    spring.mail.properties.mail.smtp.starttls.enable=true
    logging.level.org.springframework.mail=DEBUG
    logging.level.org.eclipse.angus.mail=DEBUG

    server.address=0.0.0.0
    server.port=8080

    vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    vnpay.returnUrl=http://localhost:8080/payment-callback
    vnpay.tmnCode=29SINUN5
    vnpay.hashSecret=UBLHC6WSNE9LHT0H78TMKIQU78L6OFKA
    vnpay.apiUrl=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction


    cloudinary.cloud-name=dfn4s07dp
    cloudinary.api-key=114517371317448
    cloudinary.api-secret=VI6-K0_ePD57ktGETaDhO8vbVQU
